
################ Validation config ################

### PCR primers trimming sequences (with PANDAseq for vsearch approach and Cutadapt for DADA2)
Trim_primers: True # False to skip primers trimming (usefull if unkown primers or already trimmed in the input reads, for instance for SRA deposited reads)
forward_primer: CCTACGGGNGGCWGCAG # CCTACGGGNGGCWGCAG for Illumina V3V4
reverse_primer: GACTACHVGGGTATCTAATCC # GACTACHVGGGTATCTAATCC for Illumina V3V4

### Merged sequences length-based filtering (appied to DADA2 and vsearch approaches)
merged_min_length: 390 # from 390 to 400 for V3V4
merged_max_length: 500 # from 450 to 500 for V3V4
mismatch: 3 #0 - 3 mismatch
threeprime: 2 # Number of match at the 3' end for a hit to be considered


### Database used for taxonomic assignment
tax_DB_path: "/data/databases/amplicon_based_metagenomics/16S/"
tax_DB_name: [ezbiocloud201805.202005] # must be the name of the folder containing files named "DB_amp.fasta" and "DB_amp_taxonomy.txt" in /data/. Can be multiple.
classifier: ["qiimerdp"]

### Processing for comparison of taxonomic assignment
viz_replace_empty_tax: TRUE

########### Assembly finder config ################

input_table_path: '16S_input_table_insilico.tsv'

NCBI_key: '6dce38824889f62e188a25ae35c52a083c08'
NCBI_email: 'valentin.scherz@chuv.ch'

##Parameters for search_assemblies function
#This set of parameters is to search all possible assemblies
complete_assemblies: False
reference_assemblies: False
representative_assemblies: False
exclude_from_metagenomes: True
Genbank_assemblies: True
Refseq_assemblies: True


##Parameters for the filtering function

Rank_to_filter_by: 'None'
#None: Assemblies are ranked by their assembly status (complete or not)
#and Refseq category (reference, representative ...)
#If you want to filter by species, set this parameter to 'species'. The filtering function will list all unique species
#and rank their assemblies according to assembly status and Refseq category.



